[package]
name = "nova-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["fdb-backend"]
fdb-backend = ["dep:foundationdb"]

[dependencies]
nova-common = { path = "../nova-common" }
arrow = { workspace = true }
parquet = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
foyer = { workspace = true }
chrono = "0.4"
async-trait = "0.1"
foundationdb = { version = "0.10", features = ["fdb-7_4", "embedded-fdb-include"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tempfile = "3"
