[package]
name = "nova-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
fdb-backend = ["nova-storage/fdb-backend"]

[[bin]]
name = "nova"
path = "src/main.rs"

[dependencies]
nova-common = { path = "../nova-common" }
nova-coordinator = { path = "../nova-coordinator" }
nova-worker = { path = "../nova-worker" }
nova-storage = { path = "../nova-storage" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
figment = { workspace = true }
clap = { version = "4", features = ["derive"] }
anyhow.workspace = true
object_store = { workspace = true }
serde = { workspace = true }
axum = "0.8"
tonic = "0.14"
