[package]
name = "nova-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nova-common = { path = "../nova-common" }
nova-storage = { path = "../nova-storage" }
arrow = { workspace = true }
datafusion = { workspace = true }
parquet = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
foyer = { workspace = true }
tonic = "0.12"
futures = "0.3.32"
tokio-stream = "0.1.18"
async-trait = "0.1"

[dev-dependencies]
criterion = "0.8.2"
tempfile = "3.27.0"

[[bench]]
name = "clickbench"
harness = false
